name: nene

services:
  nene:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped
    env_file:
      - .env
    networks:
      - shared

networks:
  shared:
    external: true
    name: shared
