name: nene

services:
  nene:
    image: ghcr.io/fish-lovers-1/nene-bot:${IMAGE_TAG}

    restart: unless-stopped
    env_file:
      - .env
    networks:
      - shared

networks:
  shared:
    external: true
    name: shared
