"""move db to tz less for sqlite compatibility

Revision ID: ecc0563ecc1a
Revises: f5b582460d36
Create Date: 2026-08-20 21:53:31.850109

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ecc0563ecc1a"
down_revision: str | Sequence[str] | None = "f5b582460d36"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    op.alter_column(
        "lore",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(timezone=False),
        postgresql_using="created_at AT TIME ZONE 'Australia/Sydney'",
    )

    op.alter_column(
        "lore",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(timezone=False),
        postgresql_using="created_at AT TIME ZONE 'Australia/Sydney'",
    )

    op.alter_column(
        "lore",
        "optional_timestamp",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(timezone=False),
        postgresql_using="created_at AT TIME ZONE 'Australia/Sydney'",
        existing_nullable=True,
        nullable=True,
    )

    op.alter_column(
        "user",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(timezone=False),
        postgresql_using="created_at AT TIME ZONE 'Australia/Sydney'",
    )

    op.alter_column(
        "user",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(timezone=False),
        postgresql_using="created_at AT TIME ZONE 'Australia/Sydney'",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
