"""fix db tz issue

Revision ID: f5b582460d36
Revises: 67d75bcdb67d
Create Date: 2026-08-19 23:29:33.172216

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5b582460d36"
down_revision: str | Sequence[str] | None = "67d75bcdb67d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    if bind.dialect.name == "postgresql":
        op.alter_column(
            "lore",
            "optional_timestamp",
            type_=sa.DateTime(timezone=True),
            postgresql_using=("optional_timestamp AT TIME ZONE 'Australia/Sydney'"),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
