name: Deploy Nene

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/nene-bot:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest

    needs: 
      - test
      - build

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Create env
        env:
          CF_ACCESS_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
          CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}

          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GUILD_ID: ${{ secrets.GUILD_ID }}

        run: |
          cat > .env <<EOF
          CF_ACCESS_CLIENT_ID=$CF_ACCESS_CLIENT_ID
          CF_ACCESS_CLIENT_SECRET=$CF_ACCESS_CLIENT_SECRET

          DATABASE_URL=$DATABASE_URL
          DISCORD_TOKEN=$DISCORD_TOKEN
          GUILD_ID=$GUILD_ID
          EOF

      - name: deploy
        env:
          CF_ACCESS_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
          CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}

        run: |
          curl --fail-with-body \
          -X POST "$DEPLOY_URL" \
          -H "CF-Access-Client-Id: $CF_ACCESS_CLIENT_ID" \
          -H "CF-Access-Client-Secret: $CF_ACCESS_CLIENT_SECRET" \
          -H "Authorization: Bearer $DEPLOY_TOKEN" \
          -F "env_file=@.env" \
          -F "compose_file=@compose.yml" \
          -F "image_tag=$GITHUB_SHA"


      - name: Remove env
        if: always()
        run: rm -f .env
